apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesage
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fdebar/kubesage.git
      targetRevision: v0.2.5
      path: charts/kubesage
      helm:
        valueFiles:
          - $values/environments/dev/kubesage.yaml
    - repoURL: https://github.com/fdebar/kubesage-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kubesage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
