apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fdebar/kubesage.git
    targetRevision: main
    path: charts/kubesage
    helm:
      valueFiles:
        - ../../gitops/environments/dev/kubesage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubesage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true