apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fdebar/kubesage.git
    targetRevision: main
    path: gitops/charts/monitoring
    helm:
      valueFiles:
        - ../../environments/dev/alloy.yaml
        - ../../environments/dev/loki.yaml
        - ../../environments/dev/grafana.yaml
        - ../../environments/dev/tempo.yaml
        - ../../environments/dev/open-telemetry.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
