apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fdebar/kubesage-gitops.git
      targetRevision: main
      path: charts/monitoring
      helm:
        valueFiles:
          - $values/environments/dev/alloy.yaml
          - $values/environments/dev/grafana.yaml
          - $values/environments/dev/loki.yaml
          - $values/environments/dev/open-telemetry.yaml
          - $values/environments/dev/tempo.yaml
    - repoURL: https://github.com/fdebar/kubesage-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
